import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { getAdminProfile, getAdminSessionToken, type AdminProfile } from "@/lib/server/admin-overview";

type Detail = { label: string; value: string };
function display(value: string | null): string { return value && value.trim() ? value : "--"; }
function formatDate(value: string | null): string { if (!value) return "--"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString("en-NG", { dateStyle: "medium", timeStyle: "short" }); }
function ProfileField({ label, value, type = "text" }: { label: string; value: string; type?: string }) {
  return <label className="block"><span className="text-[13px] font-bold text-admin-ink">{label}</span><input disabled type={type} value={value} readOnly className="mt-2 h-11 w-full rounded-[8px] border border-admin-border bg-admin-soft px-3 text-[14px] text-admin-ink outline-none" /></label>;
}
function EditProfile({ profile }: { profile: AdminProfile }) {
  return <section className="rounded-[10px] border border-admin-border bg-white px-6 py-7 admin-panel-shadow"><div className="flex items-start justify-between gap-5 border-b border-admin-border pb-5"><div><p className="text-[13px] font-bold uppercase text-admin-muted">Administrator profile</p><h2 className="mt-2 text-[22px] font-bold text-admin-ink">Edit profile</h2><p className="mt-1 text-[14px] text-admin-muted">Review the profile fields connected to your administrator account.</p></div><Link href="/profile" className="rounded-[8px] border border-admin-border px-4 py-2.5 text-[13px] font-bold text-admin-muted">Cancel</Link></div><div className="mt-6 rounded-[8px] border border-admin-yellow/30 bg-admin-yellow-soft px-4 py-3 text-[13px] leading-5 text-admin-warning">Profile editing is not available yet because the backend currently exposes only the read-only <span className="font-bold">GET /admin/me</span> endpoint.</div><div className="mt-6 grid gap-5 md:grid-cols-2"><ProfileField label="Full name" value={profile.fullName} /><ProfileField label="Email address" value={profile.email} type="email" /><ProfileField label="Phone number" value={display(profile.phone)} /><ProfileField label="Timezone" value={display(profile.timezone)} /><ProfileField label="Locale" value={display(profile.locale)} /><ProfileField label="Administrator role" value={display(profile.adminRole ?? profile.role).replaceAll("_", " ")} /></div><div className="mt-7 flex justify-end border-t border-admin-border pt-5"><button type="button" disabled className="rounded-[8px] bg-admin-disabled px-5 py-3 text-[14px] font-bold text-admin-muted">Save changes unavailable</button></div></section>;
}
function ProfileCard({ profile }: { profile: AdminProfile }) {
  const details: Detail[] = [
    { label: "Email address", value: profile.email },
    { label: "Phone number", value: display(profile.phone) },
    { label: "Role", value: display(profile.adminRole ?? profile.role).replaceAll("_", " ") },
    { label: "Account status", value: display(profile.status).replaceAll("_", " ") },
    { label: "Timezone", value: display(profile.timezone) },
    { label: "Locale", value: display(profile.locale) },
  ];
  return <><section className="rounded-[10px] border border-admin-border bg-white px-6 py-7 admin-panel-shadow"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-full bg-admin-blue-soft text-[28px] font-bold text-admin-blue">{profile.avatarUrl ? <Image src={profile.avatarUrl} alt="" width={96} height={96} className="h-full w-full object-cover" /> : profile.initials}</div><div><p className="text-[13px] font-bold uppercase text-admin-muted">Administrator profile</p><h2 className="mt-2 text-[28px] font-bold text-admin-ink">{profile.fullName}</h2><p className="mt-2 text-[15px] text-admin-muted">{display(profile.adminRole ?? profile.role).replaceAll("_", " ")}</p></div><Link href="/profile?edit=1" className="rounded-[8px] border border-admin-blue px-4 py-2.5 text-[13px] font-bold text-admin-blue">Edit profile</Link></div><dl className="mt-8 grid gap-5 border-t border-admin-border pt-7 sm:grid-cols-2">{details.map((detail) => <div key={detail.label}><dt className="text-[12px] font-bold uppercase text-admin-muted">{detail.label}</dt><dd className="mt-2 text-[15px] font-semibold capitalize text-admin-ink">{detail.value}</dd></div>)}</dl></section><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-[10px] border border-admin-border bg-white px-6 py-6 admin-panel-shadow"><h3 className="text-[18px] font-bold text-admin-ink">Access permissions</h3><p className="mt-1 text-[13px] text-admin-muted">Permissions currently assigned to this administrator.</p><div className="mt-5 flex flex-wrap gap-2">{profile.permissions.length ? profile.permissions.map((permission) => <span key={permission} className="rounded-full bg-admin-blue-soft px-3 py-2 text-[12px] font-bold capitalize text-admin-blue">{permission.replaceAll("_", " ")}</span>) : <p className="text-[14px] text-admin-muted">No permissions returned.</p>}</div></section><section className="rounded-[10px] border border-admin-border bg-white px-6 py-6 admin-panel-shadow"><h3 className="text-[18px] font-bold text-admin-ink">Account activity</h3><dl className="mt-5 space-y-4"><div className="flex items-center justify-between gap-4 border-b border-admin-border pb-4"><dt className="text-[13px] text-admin-muted">Last login</dt><dd className="text-right text-[13px] font-semibold text-admin-ink">{formatDate(profile.lastLoginAt)}</dd></div><div className="flex items-center justify-between gap-4"><dt className="text-[13px] text-admin-muted">Account created</dt><dd className="text-right text-[13px] font-semibold text-admin-ink">{formatDate(profile.createdAt)}</dd></div></dl></section></div></>;
}
export default async function ProfilePage({ searchParams }: { searchParams: Promise<{ edit?: string }> }) {
  const token = await getAdminSessionToken();
  if (!token) redirect("/login");
  const profile = await getAdminProfile(token);
  const params = await searchParams;
  return <main className="px-6 py-7 lg:px-8"><div className="mb-7"><p className="text-[13px] font-bold uppercase text-admin-muted">Account</p><h1 className="mt-2 text-[28px] font-bold text-admin-ink">Profile</h1><p className="mt-2 text-[15px] text-admin-muted">Review your administrator account and access.</p></div>{profile ? params.edit === "1" ? <EditProfile profile={profile} /> : <ProfileCard profile={profile} /> : <section className="grid min-h-[360px] place-items-center rounded-[10px] border border-admin-border bg-white px-6 text-center admin-panel-shadow"><div><h2 className="text-[24px] font-bold text-admin-ink">Profile unavailable</h2><p className="mt-3 max-w-md text-[14px] leading-6 text-admin-muted">Your administrator profile could not be loaded.</p></div></section>}</main>;
}
